import React, {HTMLAttributes} from "react";
// import {PickOptional} from "type/definition";

// Attention: This file is generated by "yarn icon", do not modify

export enum IconClass {
    HIDDEN_PASSWORD = "icon-hidden-password",
    SHOW_PASSWORD = "icon-show-password",
    SELECTED = "icon-selected",
    BACK_TOP = "icon-back-top",
    SERVICE = "icon-service",
    QQ = "icon-qq",
    SERVICE_ANALYSIS = "icon-service-analysis",
    INCOME_CURRENT = "icon-income-current",
    CHROME = "icon-chrome",
    FIREFOX = "icon-firefox",
    MOBILE = "icon-mobile",
    MINUS_FILL = "icon-minus-fill",
    PLUS_FILL = "icon-plus-fill",
    INCOME_BEFORE = "icon-income-before",
    CAPITAL = "icon-capital",
    SPEED_360 = "icon-speed-360",
    LOCK = "icon-lock",
    MINUS = "icon-minus",
    WECHAT = "icon-wechat",
    QUESTION = "icon-question",
    FLASH = "icon-flash",
    NONE = "icon-none",
    MENU = "icon-menu",
    ARROW_LEFT = "icon-arrow-left",
    ARROW_RIGHT = "icon-arrow-right",
    CALENDAR = "icon-calendar",
    CARET_RIGHT = "icon-caret-right",
    CARET_LEFT = "icon-caret-left",
    CHECK_SQUARE = "icon-check-square",
    CHECK = "icon-check",
    CLOSE = "icon-close",
    DELETE = "icon-delete",
    EDIT = "icon-edit",
    LOCATION = "icon-location",
    EXCLAMATION_CIRCLE_O = "icon-exclamation-circle-o",
    GIFT = "icon-gift",
    LEFT = "icon-left",
    LOGOUT = "icon-logout",
    MINUS_CIRCLE_O = "icon-minus-circle-o",
    PLUS_CIRCLE_O = "icon-plus-circle-o",
    PLUS = "icon-plus",
    QUESTION_CIRCLE_O = "icon-question-circle-o",
    QUESTION_CIRCLE = "icon-question-circle",
    RETWEET = "icon-retweet",
    RIGHT = "icon-right",
    SAFETY = "icon-safety",
    SYNC = "icon-sync",
    DOUBLE_LEFT = "icon-double-left",
    DOUBLE_RIGHT = "icon-double-right",
    ALARM = "icon-alarm",
    ARROW_DOWN = "icon-arrow-down",
    BOOKMARK = "icon-bookmark",
    CHAT = "icon-chat",
    CHART = "icon-chart",
    CLOUD_UPLOAD = "icon-cloud-upload",
    DOWNLOAD = "icon-download",
    MESSAGE = "icon-message",
    ENVELOPE_OPEN = "icon-envelope-open",
    ENVELOPE = "icon-envelope",
    FAVORITE = "icon-favorite",
    GAME = "icon-game",
    PRESENT = "icon-present",
    PROPELLER = "icon-propeller",
    ROCKET = "icon-rocket",
    PAGE = "icon-page",
    USER = "icon-user",
    USERS = "icon-users",
    CARET_DOWN = "icon-caret-down",
    BEAN = "icon-bean",
    CIRCLE = "icon-circle",
    ARROW_UP = "icon-arrow-up",
    CARET_UP = "icon-caret-up",
    FINISH = "icon-finish",
    GUARD = "icon-guard",
    HOT_POT = "icon-hot-pot",
    EXPERT_PLAN = "icon-expert-plan",
}

interface Props extends HTMLAttributes<HTMLSpanElement> {
    type: IconClass;
    text?: string;
    textPosition?: "left" | "right";
}

export default class Component extends React.PureComponent<Props> {
    // public static defaultProps: PickOptional<Props> = {
    //     textPosition: "right",
    // };

    render() {
        const {type, text, textPosition, className, ...restProps} = this.props;
        if (text) {
            if (textPosition === "left") {
                return (
                    <div className={`iconfont-with-text-on-left ${className ? className : ""}`} {...restProps}>
                        <span>{text}</span>
                        <i className={`iconfont ${type}`} {...restProps} />
                    </div>
                );
            } else {
                return (
                    <div className={`iconfont-with-text-on-right ${className ? className : ""}`} {...restProps}>
                        <i className={`iconfont ${type}`} {...restProps} />
                        <span>{text}</span>
                    </div>
                );
            }
        } else {
            return <i className={`iconfont ${type} ${className ? className : ""}`} {...restProps} />;
        }
    }
}
